///////////////////////////////////////////////////////////
//  Produto.java
//  Implementation of the Class Produto
//  Generated by Enterprise Architect
//  Created on:      15-abr-2009 00:07:21
//  Original author: fast
///////////////////////////////////////////////////////////




namespace V1 {
	public class Produto {

		private Date _data;
		private String _nome;
		private double _valor;

		public Produto(){

		}

		~Produto(){

		}

		public virtual void Dispose(){

		}

		public Date Data{
			get{
				return data;
			}
			set{
				data = value;
			}
		}

		public String Nome{
			get{
				return _nome;
			}
			set{
				_nome = value;
			}
		}

		public double Valor{
			get{
				return valor;
			}
			set{
				valor = value;
			}
		}

	}//end Produto

}//end namespace V1