///////////////////////////////////////////////////////////
//  Produto.java
//  Implementation of the Class Produto
//  Generated by Enterprise Architect
//  Created on:      15-abr-2009 00:07:21
//  Original author: fast
///////////////////////////////////////////////////////////

using System;
using System.Collections;
using System.Collections.Generic;
using financa.db;

namespace financa.model
{

    [Serializable]
    public class Produto
    {

        private DateTime _data;
        private String _nome;
        private decimal _valor;
        private string _prefixo;
        private Lancamento _lancamento;
        private int _quantidade;

        public Produto()
        {

        }

        public virtual void Dispose()
        {

        }

        public DateTime Data
        {
            get
            {
                return _data;
            }
            set
            {
                _data = value;
            }
        }

        public String Nome
        {
            get
            {
                return _nome;
            }
            set
            {
                _nome = value;
            }
        }

        public decimal Valor
        {
            get
            {
                return _valor;
            }
            set
            {
                _valor = value;
            }
        }

        public int Quantidade
        {
            get
            {
                return this._quantidade;
            }
            set
            {
                this._quantidade = value;
            }
        }

        public IList listar()
        {
            List<Produto> ps = new List<Produto>();

            try
            {
                db4o.conectar();
                foreach (Produto p in db4o.listar(this))
                { // db.Query<Conta>();
                    ps.Add(p);
                }
            }
            finally
            {
                db4o.desconectar();
            }

            return ps;
        }

        public String prefixo
        {
            get
            {
                return _prefixo;
            }
            set
            {
                _prefixo = value;
            }
        }


        public List<Produto> listar(string prefixo)
        {
            List<Produto> resultado;
            //int i = 0;

            try
            {
                db4o.conectar();
                this.prefixo = prefixo;
                resultado = ((List<Produto>)this.listar()).FindAll(comecaCom);
                /*s = new String[resultado.Count];
                foreach (Produto p in resultado)
                {
                    s[i] = p.Nome + "   -   " + p.Valor;

                    i++;
                }*/
            }
            catch (Exception e)
            {
                throw (new Exception("Problema ao listar os produtos começados com " + prefixo));
            }
            finally
            {
                db4o.desconectar();
            }

            return resultado;
        }

        private bool comecaCom(Produto p)
        {
            return p.Nome.ToUpper().StartsWith(prefixo.ToUpper());
        }

        public Lancamento lancamento
        {
            get
            {
                return this._lancamento;
            }
            set
            {
                this._lancamento = value;
            }
        }

    }//end Produto
}