///////////////////////////////////////////////////////////
//  Categoria.cs
//  Implementation of the Class Categoria
//  Generated by Enterprise Architect
//  Created on:      16-fev-2009 17:36:57
//  Original author: p016905
///////////////////////////////////////////////////////////

using System.Collections;
using System.Collections.Generic;

namespace MVCFinancas.Controllers
{
    public class Categoria
    {
        //private int _codigo;
        private string _descricao;

        public Categoria()
        {

        }

        public string descricao
        {
            get
            {
                return _descricao;
            }
            set
            {
                _descricao = value;
            }
        }

        /// 
        /// <param name="conta"></param>
        public IList listar(Conta conta)
        {
            Categoria c = new Categoria();


            ArrayList cs;

            cs = (ArrayList)db4o.listar(c);

            return cs;
        }

        public void cadastrar()
        {
            db4o.cadastrar(this);
        }


    }//end Categoria
}