///////////////////////////////////////////////////////////
//  LancamentoDebito.cs
//  Implementation of the Class LancamentoDebito
//  Generated by Enterprise Architect
//  Created on:      28-mar-2009 13:16:20
//  Original author: fast
///////////////////////////////////////////////////////////




using System.IO;
namespace MVCFinancas.Controllers
{
    public class LancamentoDebito : Lancamento
    {

        private Stream _comprovantePagamento;

        public LancamentoDebito(Stream comprovante)
        {
            this._comprovantePagamento = comprovante;
        }

        public Stream comprovantePagamento
        {
            get
            {
                return this._comprovantePagamento;
            }
            set
            {
                this._comprovantePagamento = value;
            }
        }

        public override decimal valor
        {
            get
            {
                return base._valor;
            }
            set
            {
                base._valor = decimal.Negate(value);
            }
        }

    }//end LancamentoDebito
}