///////////////////////////////////////////////////////////
//  Lancamento.cs
//  Implementation of the Class Lancamento
//  Generated by Enterprise Architect
//  Created on:      16-fev-2009 17:36:57
//  Original author: p016905
///////////////////////////////////////////////////////////

using System;
using System.Collections;
using System.Collections.Generic;

namespace MVCFinancas.Controllers
{
    public class Lancamento
    {

        private string _descricao;
        private DateTime _data;
        protected decimal _valor;
        private Usuario _usuario;
        //private Conta conta;
        //private Categoria categoria;

        public Lancamento()
        {

        }

        public string descricao
        {
            get
            {
                return _descricao;
            }
            set
            {
                _descricao = value;
            }
        }

        public DateTime data
        {
            get
            {
                return _data;
            }
            set
            {
                _data = value;
            }
        }

        public Usuario usuario
        {
            set
            {
                this._usuario = value;
            }
        }

        public virtual decimal valor
        {
            get;
            set;
        }

        public void registrar()
        {
            db4o.cadastrar(this);
        }

        public IList listar()
        {
            ArrayList cs = (ArrayList)db4o.listar(this);

            return cs;
        }

    }//end Lancamento
}